services:
  - type: web
    name: thinking-remover-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
